apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: renedo-johndeere-hpa
  namespace: renedo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: renedo-johndeere-deployment
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 100
          periodSeconds: 120
        - type: Pods
          value: 1
          periodSeconds: 120
      selectPolicy: Max
